//
// The main Jenkinsfile for FIBO, defining the Build/Publish/Test/Deploy process that is
// executed for each push into the repository.
//
// Note that this file is in the so called "Declarative Pipeline" syntax
//
// See https://jenkins.io/doc/book/pipeline/jenkinsfile/
//
pipeline {

  agent none

  options {

    buildDiscarder(
      logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
    )
    //
    // We let each stage running on each jenkins slave / agent decide what to check out or not
    //
    skipDefaultCheckout()
    //
    // Skip stages once the build status has gone to UNSTABLE.
    //
    skipStagesAfterUnstable()
    //
    // There must be SOME limit, if it hangs or whatever then that's a bug and therefore cancel the job. 6
    //
    timeout(time: 6, unit: 'HOURS')
    //
    // Prepend all console output generated by the Pipeline run with the time at which the line was emitted
    //
    //timestamps()
  }

  stages {

    stage('Prepare') {
      //
      // Run the prepare stage on the stardog node, check out all the repos there
      //
      // NOTE: For now it' the stardog node since we have more processing power there and there are things
      // installed there that we don't have on the jenkins master (such as "nix.sh")
      //
      agent {
        label 'stardog'
      }

      steps {

        //
        // Clean the workspace on this node, for now. Takes more time but we need to test this with a clean slate
        // every time. Once this all works fine we can skip this step.
        //
        sh "rm -rf ${env.WORKSPACE}/*"

        //
        // Then check out the fibo-infra repo content into the ./fibo-infra directory
        //
        dir('fibo-infra') {
          //
          // If you want to check out a specific version of fibo-infra add the "branch:" parameter
          //
          //git branch: 'INFRA-161', credentialsId: 'edmcjenkins_at_edmcouncil.org', url: 'git@github.com:edmcouncil/fibo-infra.git'
          //
          git credentialsId: 'edmcjenkins_at_edmcouncil.org', url: 'git@github.com:edmcouncil/fibo-infra.git'
          echo 'Checked out fibo-infra repo'

          dir('site') {
            stash name: 'site', includes: '**', useDefaultExcludes: true
          }
        }
        echo 'Checked it all out'
      }
    } // end of stage 'Prepare'

    //
    // Run the publish on the master jenkins agent by just copying all the static site contents right into the workspace
    // on master and let NGINX just serve it from there.
    //
    stage('Publish') {
      //
      // We only do the publication when we're on the master branch.
      //
      // TRICK: if you want to do a quick test, the disable this when{} clause in the Jenkinsfile in your branch,
      // push your changes, then Jenkins will push your version to spec.edmcouncil.org. When satisfied, move the
      // when{} back.
      //
      when {
        branch 'master'
      }
      agent {
        label 'master'
      }
      environment {
        NGINX_SPEC_ROOT = '/mnt/jenkins-disk/spec.edmcouncil.org'
      }

      steps {

        sh 'test -d ${NGINX_SPEC_ROOT}'
        sh 'pwd'
        echo "Cleaning workspace before unstashing fresh content"
        sh 'rm -rf *'

        echo 'Unstashing the static site content'
        unstash 'site'
        sh 'ls -al'
        sh 'find . -name \'.git\' -exec rm -rf {} \\; || true'
        sh 'find . -name \'.gitignore\' -exec rm -f {} \\; || true'

        echo "Copy all generated content to ${env.NGINX_SPEC_ROOT}:"
        sh 'ls -al ${NGINX_SPEC_ROOT}/'
        sh 'cp -vr . ${NGINX_SPEC_ROOT}/'
      }
    } // end of stage "Publish"
  } // end of stages

} // end of pipeline
