prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT (CONCAT("Warn:'", ?label, "' labels multiple objects.") as ?error)
WHERE 
{
    ?s rdfs:label ?label
    FILTER (REGEX (xsd:string(?s), "edmcouncil"))
}
GROUP BY ?label 
HAVING (COUNT(?label) > 1)