prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?error ?definition ?label
WHERE {
  ?s rdfs:label ?label .
  ?s skos:definition ?definition .
  FILTER NOT EXISTS {?s a owl:NamedIndividual} .
  FILTER (CONTAINS(?definition, ?label))
  FILTER (CONTAINS(str(?s), "edmcouncil"))

  BIND (
    concat ("WARN: Definition of ", str(?s), " is circular ")
      AS ?error
    )
}