prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner Deprecated resources should be monitored and removed if possible.

SELECT DISTINCT ?error
WHERE 
{
	?resource owl:deprecated ?deprecated .
	FILTER (str(?deprecated) = "true")
       
  BIND (concat ("WARN: Resource <", str(?resource), "> is deprecated.") AS ?error)
}
