PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?error
WHERE
{
    ?importingOntology owl:imports ?importedOntology.
    FILTER (CONTAINS(str(?importingOntology), "edmcouncil"))
    FILTER NOT EXISTS 
    {
        ?s ?p ?o.
        FILTER (?p NOT IN (owl:imports))
        FILTER (REGEX(str(?s), CONCAT(str(?importedOntology),".+")) || REGEX(str(?p), CONCAT(str(?importedOntology),".+")) || REGEX(str(?o), CONCAT(str(?importedOntology),".+")))
    }
    BIND (concat ("WARN: ontology ", str(?importingOntology), " does not reference any resource from imported ontology ", str(?importedOntology)) AS ?error)
}