prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner Deprecated resources should be monitored and removed if possible.

SELECT DISTINCT ?warning ?resource
WHERE 
{
	?resource owl:deprecated ?deprecated .
	FILTER (str(?deprecated) = "true")
       
  BIND (concat ("WARNING: Resource ", str(?resource), " is deprecated.") AS ?warning)
}