prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?error
WHERE 
{
  ?s rdfs:comment ?o 
  FILTER (CONTAINS(str(?s), "edmcouncil"))
  BIND (concat ("WARN: ", str(?s), " has an rdfs:comment annotation: ", str(?o)) AS ?error)
}