prefix skos: <http://www.w3.org/2004/02/skos/core#>


##
# banner Definitions should not contain the "or" connective.

SELECT ?error ?o
WHERE 
{
  ?s skos:definition ?o
  FILTER (REGEX(str(?s), "edmcouncil"))
  FILTER (REGEX (str(?o), "\\sor\\s"))
  BIND (concat ("WARN: definition of ", str(?s), " is ambiguous because of the presence of disjunction. ") AS ?error) 
} 