prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner For performance reasons we should avoid CGI axioms (with owl:equivalentClass property)

SELECT ?warning
WHERE 
{
  ?resource1 owl:equivalentClass ?resource2.
  FILTER (!ISIRI(?resource1))
  FILTER (!ISIRI(?resource2))
  
  BIND (concat ("WARN: There exists a CGI equivalent axiom") AS ?warning)
}