prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner Class subClassOf hierarchy shouldn't be circular.

SELECT DISTINCT ?error ?class
WHERE 
{
  FILTER regex(str(?class), <HYGIENE_TESTS_FILTER_PARAMETER>)
  ?class rdfs:subClassOf+ ?class .
  FILTER NOT EXISTS {?class owl:deprecated "true"^^xsd:boolean} .

  BIND (concat ("PRODERROR: There is a hierarchy cycle around class ", str(?class)) AS ?error)
}