prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner Count of deprecated resources

SELECT ("INFO: count of deprecated resources" as ?info) (COUNT(?resource) as ?count)
WHERE
{
    ?resource owl:deprecated "true"^^xsd:boolean .
}