prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner For performance reasons we should avoid equivalences with allValuesFron restrictions.

SELECT ?warning ?class
WHERE 
{
  ?resource1 owl:equivalentClass ?resource2.
  {
    FILTER (ISIRI(?resource1))
    ?resource2 rdf:type owl:Restriction.
    ?resource2 owl:allValuesFrom ?restrictingClass.

    FILTER regex(str(?resource1), <HYGIENE_TESTS_FILTER_PARAMETER>)

    BIND (?resource1 as ?class)
  }
  UNION
  {
    FILTER (ISIRI(?resource2))
    ?resource1 rdf:type owl:Restriction.
    ?resource1 owl:allValuesFrom ?restrictingClass.

    FILTER regex(str(?resource2), <HYGIENE_TESTS_FILTER_PARAMETER>)

    BIND (?resource2 as ?class)
  }
  
  BIND (concat ("WARN: There exists an equivalence axiom with allValuesFrom restriction in one side and ", ?class, " on the other.") AS ?warning)
}