prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 

##
# banner Count of OWL object properties

SELECT ("INFO: count of OWL object properties" as ?info) (COUNT(?resource) as ?count)
WHERE
{
    ?resource rdf:type/rdfs:subClassOf* owl:ObjectProperty.
}